server {
    listen 4173;
    listen [::]:4173;

    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(?:css|js|mjs|map|json|wasm|mp3|flac|wav|ogg|png|jpg|jpeg|svg|webp|ico|gz|br|utf|ttf|woff2?)$ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /sc-api/ {
        if ($request_method = 'OPTIONS') {
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
            add_header Access-Control-Allow-Headers * always;
            add_header Access-Control-Max-Age 1728000;
            add_header Content-Type "text/plain; charset=utf-8";
            add_header Content-Length 0;
            return 204;
        }

        proxy_pass https://api-v2.soundcloud.com/;
        proxy_set_header Host api-v2.soundcloud.com;
        proxy_set_header Origin https://soundcloud.com;
        proxy_set_header Referer https://soundcloud.com/;
        proxy_set_header User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36";
        proxy_ssl_server_name on;
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
        add_header Access-Control-Allow-Headers * always;
    }
}
